/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;
import java.awt.Color;
import javax.swing.JButton;
import enviroment.EnviromentHolder;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author izhaq
 */
public class ApiProfilePanel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form ApiProfilePanel
     */
    public ApiProfilePanel() {
    	setForeground(Color.RED);
        initComponents();
        initUserPassword();
    }

    private void initUserPassword() {
    	
    	String[] usernamePassword = EnviromentHolder.getUsernamePassword();
    	if(usernamePassword != null) {
    		this.userNameTB.setText(usernamePassword[0]);
    		this.passwordTB.setText(usernamePassword[1]);
    	}
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	GridBagLayout gridBagLayout = new GridBagLayout();
    	gridBagLayout.columnWidths = new int[]{100, 96, 77, 90, 45, 61, 22, 70, 0, 104, 63, 80, 53, 0};
    	gridBagLayout.rowHeights = new int[]{33, 0};
    	gridBagLayout.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
    	gridBagLayout.rowWeights = new double[]{0.0, Double.MIN_VALUE};
    	setLayout(gridBagLayout);
    	lblUsername = new javax.swing.JLabel();

    	lblUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    	lblUsername.setText("User Name  :");
    	lblUsername.setOpaque(true);
    	GridBagConstraints gbc_lblUsername = new GridBagConstraints();
    	gbc_lblUsername.anchor = GridBagConstraints.WEST;
    	gbc_lblUsername.fill = GridBagConstraints.VERTICAL;
    	gbc_lblUsername.insets = new Insets(0, 0, 0, 5);
    	gbc_lblUsername.gridx = 0;
    	gbc_lblUsername.gridy = 0;
    	add(lblUsername, gbc_lblUsername);
    	userNameTB = new javax.swing.JTextField();
    	GridBagConstraints gbc_userNameTB = new GridBagConstraints();
    	gbc_userNameTB.fill = GridBagConstraints.BOTH;
    	gbc_userNameTB.insets = new Insets(0, 0, 0, 5);
    	gbc_userNameTB.gridx = 1;
    	gbc_userNameTB.gridy = 0;
    	add(userNameTB, gbc_userNameTB);
    	lblPass = new javax.swing.JLabel();

    	lblPass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    	lblPass.setText("Password  :");
    	lblPass.setOpaque(true);
    	GridBagConstraints gbc_lblPass = new GridBagConstraints();
    	gbc_lblPass.fill = GridBagConstraints.BOTH;
    	gbc_lblPass.insets = new Insets(0, 0, 0, 5);
    	gbc_lblPass.gridx = 2;
    	gbc_lblPass.gridy = 0;
    	add(lblPass, gbc_lblPass);
    	passwordTB = new javax.swing.JTextField();
    	
    	GridBagConstraints gbc_passwordTB = new GridBagConstraints();
    	gbc_passwordTB.fill = GridBagConstraints.BOTH;
    	gbc_passwordTB.insets = new Insets(0, 0, 0, 5);
    	gbc_passwordTB.gridx = 3;
    	gbc_passwordTB.gridy = 0;
    	add(passwordTB, gbc_passwordTB);

    	jLabel12 = new javax.swing.JLabel();

    	jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    	jLabel12.setText("Host  :");
    	jLabel12.setOpaque(true);
    	GridBagConstraints gbc_jLabel12 = new GridBagConstraints();
    	gbc_jLabel12.fill = GridBagConstraints.BOTH;
    	gbc_jLabel12.insets = new Insets(0, 0, 0, 5);
    	gbc_jLabel12.gridx = 4;
    	gbc_jLabel12.gridy = 0;
    	add(jLabel12, gbc_jLabel12);
    	hostTB = new javax.swing.JTextField();
    	hostTB.setEditable(false);
    	hostTB.setForeground(Color.GRAY);
    	hostTB.setText("snv4914");
    	GridBagConstraints gbc_hostTB = new GridBagConstraints();
    	gbc_hostTB.fill = GridBagConstraints.BOTH;
    	gbc_hostTB.insets = new Insets(0, 0, 0, 5);
    	gbc_hostTB.gridx = 5;
    	gbc_hostTB.gridy = 0;
    	add(hostTB, gbc_hostTB);

    	btnConnect = new JButton("Connect");
    	btnConnect.addActionListener(this);
    	
    	
    	GridBagConstraints gbc_btnConnect = new GridBagConstraints();
    	gbc_btnConnect.gridwidth = 2;
    	gbc_btnConnect.insets = new Insets(0, 0, 0, 5);
    	gbc_btnConnect.gridx = 6;
    	gbc_btnConnect.gridy = 0;
    	add(btnConnect, gbc_btnConnect);
    	lblBB = new javax.swing.JLabel();

    	lblBB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    	lblBB.setText("BB  :");
    	lblBB.setOpaque(true);
    	GridBagConstraints gbc_lblBB = new GridBagConstraints();
    	gbc_lblBB.insets = new Insets(0, 0, 0, 5);
    	gbc_lblBB.fill = GridBagConstraints.BOTH;
    	gbc_lblBB.gridx = 8;
    	gbc_lblBB.gridy = 0;
    	add(lblBB, gbc_lblBB);

    	lblLblbuildingblock = new JLabel("1");
    	lblLblbuildingblock.setForeground(Color.RED);
    	GridBagConstraints gbc_lblLblbuildingblock = new GridBagConstraints();
    	gbc_lblLblbuildingblock.insets = new Insets(0, 0, 0, 5);
    	gbc_lblLblbuildingblock.gridx = 9;
    	gbc_lblLblbuildingblock.gridy = 0;
    	add(lblLblbuildingblock, gbc_lblLblbuildingblock);
    	lblHost = new javax.swing.JLabel();

    	lblHost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    	lblHost.setText("CCVR  :");
    	lblHost.setOpaque(true);
    	GridBagConstraints gbc_lblHost = new GridBagConstraints();
    	gbc_lblHost.fill = GridBagConstraints.BOTH;
    	gbc_lblHost.insets = new Insets(0, 0, 0, 5);
    	gbc_lblHost.gridx = 10;
    	gbc_lblHost.gridy = 0;
    	add(lblHost, gbc_lblHost);

    	lblLblccversion = new JLabel("1");
    	lblLblccversion.setForeground(Color.RED);
    	GridBagConstraints gbc_lblLblccversion = new GridBagConstraints();
    	gbc_lblLblccversion.insets = new Insets(0, 0, 0, 5);
    	gbc_lblLblccversion.gridx = 11;
    	gbc_lblLblccversion.gridy = 0;
    	add(lblLblccversion, gbc_lblLblccversion);

    }// </editor-fold>//GEN-END:initComponents


    private javax.swing.JTextField hostTB;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblBB;
    private javax.swing.JTextField passwordTB;
    private javax.swing.JTextField userNameTB;
    private JLabel lblLblbuildingblock;
    private JLabel lblLblccversion;
    private JButton btnConnect;
    
    // End of variables declaration//GEN-END:variables
	public void actionPerformed(ActionEvent arg0) {
		
//        boolean isAuthenticated;
//		try {
//			
//			Connection conn = null;Session sess = null;
//	        conn = new Connection(hostTB.getText());
//	        conn.connect();
//			isAuthenticated = conn.authenticateWithPassword(userNameTB.getText(), passwordTB.getText());
//	        if (!isAuthenticated) throw new IOException("Authentication failed.");
//	        sess = conn.openSession();
//
//	        //new Thread(new SyncPipe(sess.getStderr(), System.err)).start();
//	        //new Thread(new SyncPipe(sess.getStdout(), System.out)).start();
//	        sess.requestPTY("bash");
//	        sess.startShell();
//	        
//	
//	        byte[] output = new byte[500];
//	        sess.getStdout().read(output);
//	        System.out.println(sess);
//	        
//	        
//		} catch (IOException e) {
//
//			e.printStackTrace();
//		}

		
	}
}
