/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author izhaq
 */
public class GeneralPanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneralPanel
     */
    public GeneralPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTlgServerBTN = new javax.swing.JButton();
        refreahLocalBTN = new javax.swing.JButton();
        startTlgServerBTN = new javax.swing.JButton();
        stopTlgServerBTN = new javax.swing.JButton();
        setTlgEnvBTN = new javax.swing.JButton();

        refreshTlgServerBTN.setText("RefreshTlgServer");

        refreahLocalBTN.setText("RefreshLocal");

        startTlgServerBTN.setText("StartTlgServer");

        stopTlgServerBTN.setText("StopTlgServer");
        stopTlgServerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopTlgServerBTNActionPerformed(evt);
            }
        });

        setTlgEnvBTN.setText("SetTlgEnv");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(refreahLocalBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshTlgServerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stopTlgServerBTN)
                        .addGap(118, 118, 118)
                        .addComponent(setTlgEnvBTN))
                    .addComponent(startTlgServerBTN))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshTlgServerBTN)
                    .addComponent(stopTlgServerBTN)
                    .addComponent(setTlgEnvBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreahLocalBTN)
                    .addComponent(startTlgServerBTN))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stopTlgServerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopTlgServerBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopTlgServerBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton refreahLocalBTN;
    private javax.swing.JButton refreshTlgServerBTN;
    private javax.swing.JButton setTlgEnvBTN;
    private javax.swing.JButton startTlgServerBTN;
    private javax.swing.JButton stopTlgServerBTN;
    // End of variables declaration//GEN-END:variables
}
