/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;

/**
 *
 * @author izhaq
 */
public class GeneralPanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneralPanel
     */
    public GeneralPanel() {
        initComponents();
    }

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	GridBagLayout gridBagLayout = new GridBagLayout();
    	gridBagLayout.columnWidths = new int[]{117, 55, 0};
    	gridBagLayout.rowHeights = new int[]{23, 23, 23, 0};
    	gridBagLayout.columnWeights = new double[]{0.0, 0.0, Double.MIN_VALUE};
    	gridBagLayout.rowWeights = new double[]{0.0, 0.0, 0.0, Double.MIN_VALUE};
    	setLayout(gridBagLayout);

    	refreshTlgServerBTN = new javax.swing.JButton();

    	refreshTlgServerBTN.setText("RefreshTlgServer");
    	GridBagConstraints gbc_refreshTlgServerBTN = new GridBagConstraints();
    	gbc_refreshTlgServerBTN.anchor = GridBagConstraints.NORTHWEST;
    	gbc_refreshTlgServerBTN.insets = new Insets(0, 0, 5, 5);
    	gbc_refreshTlgServerBTN.gridx = 0;
    	gbc_refreshTlgServerBTN.gridy = 0;
    	add(refreshTlgServerBTN, gbc_refreshTlgServerBTN);
    	stopTlgServerBTN = new javax.swing.JButton();

    	stopTlgServerBTN.setText("StopTlgServer");

    	stopTlgServerBTN.addActionListener(new java.awt.event.ActionListener() {
    		public void actionPerformed(java.awt.event.ActionEvent evt) {
    			stopTlgServerBTNActionPerformed(evt);
    		}
    	});
    	GridBagConstraints gbc_stopTlgServerBTN = new GridBagConstraints();
    	gbc_stopTlgServerBTN.anchor = GridBagConstraints.NORTHEAST;
    	gbc_stopTlgServerBTN.insets = new Insets(0, 0, 5, 0);
    	gbc_stopTlgServerBTN.gridx = 1;
    	gbc_stopTlgServerBTN.gridy = 0;
    	add(stopTlgServerBTN, gbc_stopTlgServerBTN);
    	
    	setTlgEnvBTN = new javax.swing.JButton();
    	setTlgEnvBTN.setText("SetTlgEnv");
    	GridBagConstraints gbc_setTlgEnvBTN = new GridBagConstraints();
    	gbc_setTlgEnvBTN.anchor = GridBagConstraints.NORTHWEST;
    	gbc_setTlgEnvBTN.insets = new Insets(0, 0, 5, 5);
    	gbc_setTlgEnvBTN.gridx = 0;
    	gbc_setTlgEnvBTN.gridy = 1;
    	add(setTlgEnvBTN, gbc_setTlgEnvBTN);
    	
    	refreahLocalBTN = new javax.swing.JButton();
    	refreahLocalBTN.setText("RefreshLocal");
    	GridBagConstraints gbc_refreahLocalBTN = new GridBagConstraints();
    	gbc_refreahLocalBTN.anchor = GridBagConstraints.NORTH;
    	gbc_refreahLocalBTN.fill = GridBagConstraints.HORIZONTAL;
    	gbc_refreahLocalBTN.insets = new Insets(0, 0, 0, 5);
    	gbc_refreahLocalBTN.gridx = 0;
    	gbc_refreahLocalBTN.gridy = 2;
    	add(refreahLocalBTN, gbc_refreahLocalBTN);
    	
    	startTlgServerBTN = new javax.swing.JButton();
    	startTlgServerBTN.setText("StartTlgServer");
    	GridBagConstraints gbc_startTlgServerBTN = new GridBagConstraints();
    	gbc_startTlgServerBTN.anchor = GridBagConstraints.NORTHWEST;
    	gbc_startTlgServerBTN.gridx = 1;
    	gbc_startTlgServerBTN.gridy = 2;
    	add(startTlgServerBTN, gbc_startTlgServerBTN);
    	
    }// </editor-fold>//GEN-END:initComponents

    private void stopTlgServerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopTlgServerBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopTlgServerBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton refreahLocalBTN;
    private javax.swing.JButton refreshTlgServerBTN;
    private javax.swing.JButton setTlgEnvBTN;
    private javax.swing.JButton startTlgServerBTN;
    private javax.swing.JButton stopTlgServerBTN;
    // End of variables declaration//GEN-END:variables
}
