/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import enviroment.Constants;
import eventHendlers.localBuildHandler;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 *
 * @author izhaq
 */
public class RunLocalBuildPanel extends javax.swing.JPanel {

    /**
     * Creates new form RunLocalBuildPanel
     */
    public RunLocalBuildPanel() {
        initComponents();
        initHandlers();
    }
    
    private void initHandlers() 
    {
        startBTN.addActionListener(new localBuildHandler());
        endBTN.addActionListener(new localBuildHandler());
        checkLogBTN.addActionListener(new localBuildHandler());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandLabel = new javax.swing.JLabel();
        
        commandDDL = new javax.swing.JComboBox();
        
        refreshLocalCB = new javax.swing.JCheckBox();
        refreshTlgServerCB = new javax.swing.JCheckBox();
        restartServerCB = new javax.swing.JCheckBox();
        
        checkLogBTN = new javax.swing.JButton();
        startBTN = new javax.swing.JButton();
        endBTN = new javax.swing.JButton();

        commandLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        commandLabel.setText("Command :");
        commandLabel.setOpaque(true);

        commandDDL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        
        refreshLocalCB.setText(Constants.REFRESH_LOCAL);
        refreshTlgServerCB.setText(Constants.REFRESH_TLG_SERVER);
        restartServerCB.setText(Constants.RESTART_TLG_SERVER);
        
        checkLogBTN.setText(Constants.CHECK_LOG);
        startBTN.setText(Constants.START);
        endBTN.setText(Constants.END);
        
        endBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(startBTN, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(endBTN, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        				.addComponent(restartServerCB)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(commandLabel)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(commandDDL, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
        				.addComponent(checkLogBTN)
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(refreshLocalCB, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(refreshTlgServerCB, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        			.addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(commandLabel)
        				.addComponent(commandDDL, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(refreshLocalCB, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(refreshTlgServerCB)
        			.addGap(18)
        			.addComponent(restartServerCB)
        			.addGap(30)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(startBTN)
        				.addComponent(endBTN))
        			.addGap(18)
        			.addComponent(checkLogBTN)
        			.addContainerGap(40, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void endBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endBTNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkLogBTN;
    private javax.swing.JComboBox commandDDL;
    private javax.swing.JButton endBTN;
    private javax.swing.JLabel commandLabel;
    private javax.swing.JCheckBox refreshLocalCB;
    private javax.swing.JCheckBox refreshTlgServerCB;
    private javax.swing.JCheckBox restartServerCB;
    private javax.swing.JButton startBTN;
    // End of variables declaration//GEN-END:variables
}
