/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import enviroment.Constants;
import enviroment.EnviromentHolder;
import eventHendlers.localBuildHandler;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JButton;


/**
 *
 * @author izhaq
 */
public class RunLocalBuildPanel extends javax.swing.JPanel {



	/**
     * Creates new form RunLocalBuildPanel
     */
    public RunLocalBuildPanel() {
        initComponents();
        initHandlers();
    }
    
    private void initHandlers() 
    {
        localBuildBTN.addActionListener(new localBuildHandler(this));
        endBTN.addActionListener(new localBuildHandler(this));
        checkLogBTN.addActionListener(new localBuildHandler(this));
        quickBuildBTN.addActionListener(new localBuildHandler(this));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
    	setLayout(null);
    	
        refreshLocalCB = new javax.swing.JCheckBox();
        refreshLocalCB.setBounds(4, 156, 96, 22);
        refreshTlgServerCB = new javax.swing.JCheckBox();
        refreshTlgServerCB.setBounds(4, 126, 121, 18);
        restartServerCB = new javax.swing.JCheckBox();
        restartServerCB.setBounds(4, 94, 117, 18);
        
        checkLogBTN = new javax.swing.JButton();
        checkLogBTN.setBounds(4, 238, 112, 28);
        localBuildBTN = new javax.swing.JButton();
        localBuildBTN.setBounds(6, 198, 110, 28);
        endBTN = new javax.swing.JButton();
        endBTN.setBounds(128, 198, 81, 28);
        
       
        refreshLocalCB.setText(Constants.REFRESH_LOCAL);
        refreshTlgServerCB.setText(Constants.REFRESH_TLG_SERVER);
        restartServerCB.setText(Constants.RESTART_TLG_SERVER);
        
        checkLogBTN.setText(Constants.CHECK_LOCAL_BUILD_LOG);
        localBuildBTN.setText(Constants.RUN_LOCAL_BUILD);
        endBTN.setText(Constants.END);
        

               
        
        add(endBTN);
        add(checkLogBTN);
        add(localBuildBTN);
        add(restartServerCB);
        add(refreshTlgServerCB);
        add(refreshLocalCB);
        
    	lblBb = new JLabel("BB:");
    	lblBb.setBounds(6, 6, 25, 26);
    	lblBb.setFont(new Font("Tahoma", Font.PLAIN, 13));
    	add(lblBb);
    	
    	bbDDL = new javax.swing.JComboBox();
    	bbDDL.setBounds(61, 6, 125, 26);
    	bbDDL.setToolTipText("Select BB to run build");
    	bbDDL.setMaximumRowCount(20);
    	bbDDL.setModel(new javax.swing.DefaultComboBoxModel(EnviromentHolder.getDdlForBB()));
    	add(bbDDL);

    	lblVersion = new JLabel("Version:");
    	lblVersion.setBounds(6, 49, 57, 17);
    	lblVersion.setFont(new Font("Tahoma", Font.PLAIN, 13));
    	add(lblVersion);

    	versionsDDL = new JComboBox();
    	versionsDDL.setBounds(61, 44, 125, 26);
    	versionsDDL.setToolTipText("Select version");
    	versionsDDL.setModel(new javax.swing.DefaultComboBoxModel(EnviromentHolder.getDdlForVersions()));
    	add(versionsDDL);
    	
    	quickBuildBTN = new JButton(Constants.RUN_QUICK_BUILD);
    	quickBuildBTN.setBounds(4, 280, 112, 28);
    	add(quickBuildBTN);


    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkLogBTN;
    private javax.swing.JButton endBTN;
    public javax.swing.JCheckBox refreshLocalCB;
    public javax.swing.JCheckBox refreshTlgServerCB;
    public javax.swing.JCheckBox restartServerCB;
    private javax.swing.JButton localBuildBTN;
    private JLabel lblVersion;
	private JComponent lblBb;
	private JComboBox bbDDL;
	private JComboBox versionsDDL;
	private JButton quickBuildBTN;
	
	
	public JComboBox getBbDDL() {
		return bbDDL;
	}

	public JComboBox getVersionsDDL() {
		return versionsDDL;
	}
}
